# Generated by Django 5.1.4 on 2025-07-25 10:43

import two.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0002_remove_registration_mothers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='seat_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='aadhar_pic',
            field=models.ImageField(upload_to=two.models.aadhar_upload_path),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pic',
            field=models.ImageField(upload_to=two.models.photo_upload_path),
        ),
    ]
